# Generated by Django 4.1.1 on 2022-09-22 04:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "other_names",
                    models.CharField(max_length=100, verbose_name="Other Names"),
                ),
                (
                    "student_id",
                    models.CharField(max_length=8, verbose_name="Student ID Number"),
                ),
                (
                    "index_number",
                    models.CharField(max_length=8, verbose_name="Student Index Number"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("100", "100"),
                            ("200", "200"),
                            ("300", "300"),
                            ("400", "400"),
                        ],
                        max_length=3,
                        verbose_name="Level of Student",
                    ),
                ),
            ],
        ),
    ]
