# Generated by Django 4.1.1 on 2022-09-22 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Course Name")),
                ("code", models.CharField(max_length=10, verbose_name="Course Code")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("100", "100"),
                            ("200", "200"),
                            ("300", "300"),
                            ("400", "400"),
                        ],
                        default="100",
                        max_length=3,
                        verbose_name="Level",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Programme Name"),
                ),
                ("college", models.CharField(max_length=100, verbose_name="College")),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="Name")),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[
                    ("100", "100"),
                    ("200", "200"),
                    ("300", "300"),
                    ("400", "400"),
                ],
                default="100",
                max_length=3,
                verbose_name="Level of Student",
            ),
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="Start Date and Time")),
                ("end", models.DateTimeField(verbose_name="End Date and Time")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associated_exams",
                        related_query_name="associated_exam",
                        to="students.course",
                    ),
                ),
                (
                    "invigilators",
                    models.ManyToManyField(
                        limit_choices_to={"invigilator": True},
                        related_name="assigned_exams",
                        related_query_name="assigned_exam",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("room", models.ManyToManyField(to="students.room")),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="programme_of_study",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                related_query_name="student",
                to="students.programme",
            ),
        ),
    ]
