# Generated by Django 4.1.1 on 2022-09-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_student_programme_of_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="students",
            field=models.ManyToManyField(
                related_name="registered_exams",
                related_query_name="registered_exam",
                to="students.student",
            ),
        ),
    ]
