# Generated by Django 4.1.1 on 2022-09-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_exam_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="other_names",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Other Names"
            ),
        ),
    ]
