# Generated by Django 4.1.1 on 2022-09-22 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0006_alter_student_other_names"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="room",
            new_name="rooms",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="invigilators",
        ),
        migrations.AddField(
            model_name="room",
            name="capacity",
            field=models.IntegerField(default=30, verbose_name="Room Capacity"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="invigilators",
            field=models.ManyToManyField(
                limit_choices_to={"invigilator": True},
                related_name="assigned_exams",
                related_query_name="assigned_exam",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="students",
            field=models.ManyToManyField(
                related_name="allocated_rooms",
                related_query_name="allocated_room",
                to="students.student",
            ),
        ),
    ]
