# Generated by Django 4.1.1 on 2022-09-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_rename_room_exam_rooms_remove_exam_invigilators_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="level",
            field=models.CharField(
                choices=[
                    ("100", "100"),
                    ("200", "200"),
                    ("300", "300"),
                    ("400", "400"),
                ],
                default="100",
                max_length=3,
                verbose_name="Level",
            ),
        ),
    ]
