# Generated by Django 4.1.1 on 2022-09-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_exam_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="course",
        ),
        migrations.AddField(
            model_name="exam",
            name="course_code",
            field=models.CharField(
                default="", max_length=10, verbose_name="Course Code"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exam",
            name="course_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Course Name"
            ),
            preserve_default=False,
        ),
    ]
