# Generated by Django 4.1.1 on 2022-09-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0011_remove_exam_students_student_registered_exams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="registered_exams",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="students",
                related_query_name="student",
                to="students.exam",
            ),
        ),
    ]
