# Generated by Django 4.1.1 on 2022-09-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0013_alter_student_registered_exams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="index_number",
            field=models.CharField(
                max_length=8, unique=True, verbose_name="Student Index Number"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                max_length=8, unique=True, verbose_name="Student ID Number"
            ),
        ),
    ]
