# Generated by Django 4.1.1 on 2022-09-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0014_alter_student_index_number_alter_student_student_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="registered_exams",
        ),
    ]
