# Generated by Django 4.1.1 on 2022-09-25 22:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("attendances", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examattendance",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
